import type { Metadata } from "next";
import { siteConfig } from "@/config/site";
import { faqs } from "@/data/faqs";

/** Stable ids so page-level schema can point at the one business entity. */
const businessId = `${siteConfig.url}/#business`;
const websiteId = `${siteConfig.url}/#website`;

/** The default share card, generated by src/app/opengraph-image.tsx. */
const defaultOgImage = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: `${siteConfig.brand.name} — vehicle booking in Salooni, Chamba`,
};

/**
 * Full metadata for one indexable page: title, description, canonical,
 * Open Graph and Twitter card.
 *
 * Next.js replaces (not merges) a parent's `openGraph` and `twitter` when a
 * page sets its own, so every page goes through this helper — otherwise inner
 * pages lose the site name, locale and share image, and the Twitter card
 * falls back to the homepage title.
 */
export function pageMetadata({
  title,
  description,
  path,
  image,
  absoluteTitle = false,
}: {
  title: string;
  description: string;
  /** Path from the site root, e.g. "/vehicles". Becomes the canonical URL. */
  path: string;
  /** Share image; defaults to the generated site card. */
  image?: { url: string; alt: string };
  /** Skips the "| Salooni Transport Hub" title template (homepage). */
  absoluteTitle?: boolean;
}): Metadata {
  const ogImage = image ?? defaultOgImage;

  return {
    title: absoluteTitle ? { absolute: title } : title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      locale: "en_IN",
      siteName: siteConfig.brand.name,
      url: path,
      title,
      description,
      images: [ogImage],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [{ url: ogImage.url, alt: ogImage.alt }],
    },
  };
}

// Where customers are picked up. Outstation drops can go anywhere, but
// the business is local to Salooni tehsil for now.
const areaServed = [
  { "@type": "City", name: "Salooni" },
  { "@type": "AdministrativeArea", name: "Chamba district, Himachal Pradesh" },
];

/**
 * LocalBusiness + WebSite structured data, rendered once in the root layout.
 *
 * Only verifiable business facts are included here. Aggregate ratings
 * are deliberately omitted: the site publishes no customer reviews, and
 * marking them up as real review data would be misleading to search
 * engines and to customers. Add an `aggregateRating` block only once
 * genuine, verifiable reviews are in place. Opening hours and map
 * coordinates are left out until the business confirms them.
 */
export const siteSchema = {
  "@context": "https://schema.org",
  "@graph": [
    {
      // Plain LocalBusiness rather than AutoRental: every vehicle comes with
      // a driver or operator, and the fleet includes trucks, tractors and JCB.
      "@type": "LocalBusiness",
      "@id": businessId,
      name: siteConfig.brand.name,
      description: siteConfig.brand.description,
      url: siteConfig.url,
      logo: `${siteConfig.url}/icon-512.png`,
      image: `${siteConfig.url}/opengraph-image`,
      telephone: siteConfig.contact.phoneNumber,
      email: siteConfig.contact.email,
      address: {
        "@type": "PostalAddress",
        addressLocality: siteConfig.contact.address.city,
        addressRegion: siteConfig.contact.address.state,
        // District is not a schema.org PostalAddress field; the locality line
        // carries the town, which is what local search matches on.
        // Omitted while unset — never publish a guessed PIN code to Google.
        ...(siteConfig.contact.address.postalCode
          ? { postalCode: siteConfig.contact.address.postalCode }
          : {}),
        addressCountry: "IN",
      },
      areaServed,
      knowsLanguage: ["en", "hi"],
    },
    {
      "@type": "WebSite",
      "@id": websiteId,
      url: siteConfig.url,
      name: siteConfig.brand.name,
      inLanguage: "en-IN",
      publisher: { "@id": businessId },
    },
  ],
};

/** Service schema for a vehicle-type landing page, tied to the business. */
export function serviceSchema({
  name,
  serviceType,
  description,
  path,
}: {
  name: string;
  serviceType: string;
  description: string;
  path: string;
}): object {
  return {
    "@context": "https://schema.org",
    "@type": "Service",
    name,
    serviceType,
    description,
    url: `${siteConfig.url}${path}`,
    provider: { "@id": businessId },
    areaServed,
  };
}

/** FAQPage schema generated from the FAQ data file. */
export const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqs.map((faq) => ({
    "@type": "Question",
    name: faq.question,
    acceptedAnswer: {
      "@type": "Answer",
      text: faq.answer,
    },
  })),
};

/**
 * Breadcrumb schema helper for inner pages. The current page may omit its
 * path — Google uses the page URL for a final item without one.
 */
export function breadcrumbSchema(
  items: { name: string; path?: string }[],
): object {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: item.name,
      ...(item.path ? { item: `${siteConfig.url}${item.path}` } : {}),
    })),
  };
}
